#!/usr/bin/env python

import RPi.GPIO as GPIO
import mcp3008
import mediorc
import sys

CHILLPIN = 17

class StateMachine(object) :
	def __init__(self, temp_probes) :
		self.chiller = False
		self.temp_probes = temp_probes
		self.i = 0
		GPIO.setup(CHILLPIN, GPIO.OUT)

	def step(self) :
		self.i += 1

		if self.i % 50 == 0 :
			self.chiller = not self.chiller

		GPIO.output(CHILLPIN, self.chiller)

class ChillmonBot(mediorc.IRC) :
	def __init__(self, server, nick, chan, temp_probes, state_machine) :
		self.temp_probes = temp_probes
		self.state_machine = state_machine
		mediorc.IRC.__init__(self, server, nick, chan)

	def on_pubmsg(self, c, e) :
		chan = e.target()
		words = e.arguments()[0].split(' ')

		msg = None
		if words[0] == '!temp' :
			msg = 'temperatures: %s' % (', '.join(['%s: %0.1f F' % (name, probe.read()) for name,probe in self.temp_probes.items()]))

		if msg :
			self.connection.privmsg(chan, msg)

	def do_work(self) :
		self.state_machine.step()

class ChillmonBotThread(mediorc.IRCThread) :
	def __init__(self, server, nick, chan, temperature_probes, state_machine) :
		self.bot_create = lambda: ChillmonBot(server, nick, chan, temperature_probes, state_machine)
		mediorc.IRCThread.__init__(self)

if __name__ == '__main__' :
	a2d = mcp3008.MCP3008(3300.0)
	beer = mcp3008.TMP36(mcp3008.TMP36.F)
	a2d.setup_channel(0, beer)
	room = mcp3008.TMP36(mcp3008.TMP36.F)
	a2d.setup_channel(1, room)
	beertop = mcp3008.TMP36(mcp3008.TMP36.F)
	a2d.setup_channel(2, beertop)

	temp_probes = {'beer' : beer, 'room' : room, 'beertop' : beertop}
	state_machine = StateMachine(temp_probes)

	chill = ChillmonBotThread(sys.argv[1], sys.argv[2], sys.argv[3], temp_probes, state_machine)
	chill.run()
